import { VariablesEnum } from "../types";

export const SELECT_VARS_COUNT_OPTIONS = [
  { value: "2", content: "2" },
  { value: "3", content: "3" },
  { value: "5", content: "5" },
  { value: "6", content: "6" },
  { value: "7", content: "7" },
  { value: "8", content: "8" },
  { value: "9", content: "9" },
  { value: "10", content: "10" },
  { value: "11", content: "11" },
  { value: "12", content: "12" },
  { value: "13", content: "13" },
  { value: "14", content: "14" },
  { value: "15", content: "15" },
  { value: "16", content: "16" },
  { value: "17", content: "17" },
  { value: "18", content: "18" },
  { value: "19", content: "19" },
  { value: "20", content: "20" },
  { value: "21", content: "21" },
  { value: "22", content: "22" },
  { value: "23", content: "23" },
  { value: "24", content: "24" },
  { value: "25", content: "25" },
  { value: "26", content: "26" },
];
export const DEFAULT_VARS_COUNT = 2;

export const MAP_VAR_NUMBER_TO_NAME: Record<string, VariablesEnum> = {
  0: VariablesEnum.A,
  1: VariablesEnum.B,
  2: VariablesEnum.C,
  3: VariablesEnum.D,
  4: VariablesEnum.E,
  5: VariablesEnum.F,
  6: VariablesEnum.G,
  7: VariablesEnum.H,
  8: VariablesEnum.I,
  9: VariablesEnum.J,
  10: VariablesEnum.K,
  11: VariablesEnum.L,
  12: VariablesEnum.M,
  13: VariablesEnum.N,
  14: VariablesEnum.O,
  15: VariablesEnum.P,
  16: VariablesEnum.Q,
  17: VariablesEnum.R,
  18: VariablesEnum.S,
  19: VariablesEnum.T,
  20: VariablesEnum.U,
  21: VariablesEnum.V,
  22: VariablesEnum.W,
  23: VariablesEnum.X,
  24: VariablesEnum.Y,
  25: VariablesEnum.Z,
};
